### ISSUE TITLE
"Finishing off" EDAM Formats curation (placeholder)

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#370]
Jobs to-do for _"Towards a comprehensive catalogue of data formats"_ article:

- [ ] Misc. addition / changes to Format concepts tracked as [issues](https://github.com/edamontology/edamontology/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22concept%2Fterm+request%22+format)
(currently mostly assigned to @matuskalas)
- [ ] Refactoring of Format (by type of data) - [names of placeholders](https://github.com/edamontology/edamontology/issues/283
)
- [ ] Refactoring of Format (by type of data) - [remodelling placeholders](https://github.com/edamontology/edamontology/issues/287) - not essential, but for consideration
- [ ] [Modelling of links ](https://github.com/edamontology/edamontologyDocs/issues/10)to info about formats
- [ ] Systematic [review ](https://github.com/edamontology/edamontology/issues/215
) of existing format concepts as per criteria checklist
- [ ] [checks ](https://github.com/edamontology/edamontology/issues/246)for consistency
- [ ] [Ensuring coverage ](https://github.com/edamontology/edamontology/issues/85)for Galaxy applications
- [ ] FAIRSharing coverage
- [ ] Misc. additions (@mkalas private spreadsheets)

**Comment by veitveit** [comment]
Collecting issues related to finishing off:
#284 (separate tabulator from pure textual formats)
